### ISSUE TITLE
Is this a fork of QSForex?

### ISSUE THREAD

**Issue by nskaggs** [eadains/QuantForex#1]
And regardless, are you interested in taking the project further? QSForex is missing a few pieces and you seem to be on the right track here. Can you explain more about the project? Will you take pull requests? What is the license?

**Comment by eadains** [comment]
It started as a fork, and sorta developed from there as I decided on some things I wanted to add. I'm not working on it at the moment just because of other stuff in life. It's intended to do pretty much what QSForex does, but I tried to make the different parts of the system more compartmentalized and independent of each other. If you want to contribute to my project, I will definitely look over any pull requests, but I would just fork it if you really want to work on it seriously. I haven't bothered with a license, but just do what you want with it, it's really just a pet project. Just be warned, I'm pretty much a novice programmer at best, so there aren't any tests, and the code is probably a bit shit to anyone who knows what they are doing.
